
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DELIMITER FA FI3L1 FI3L10 FI3L11 FI3L12 FI3L2 FI3L3 FI3L4 FI3L5 FI3L6 FI3L7 FI3L8 FI3L9 HARF1 HARF2 HARF3 HARFNAFY ISSM1 ISSM10 ISSM11 ISSM12 ISSM13 ISSM2 ISSM3 ISSM4 ISSM5 ISSM6 ISSM7 ISSM8 ISSM9 KHABAR1 MAF3OLBIH1 MAF3OLBIH2 MAF3OLBIH3 MAF3OLBIH4 MAF3OLBIH5 MAF3OLBIH6 MODAF1 MODAF2 MODAF3 MODAF4 WAWproverb : proverb_1\n                    | proverb_2\n                    | proverb_3\n                    | proverb_4\n                    | proverb_5\n                    | proverb_6\n                    | proverb_7\n                    | proverb_8\n                    | proverb_9\n                    | proverb_10\n                    | prov1\n                    | prov2\n                    | prov3\n                    | prov4\n                    | prov5\n                    | prov6\n                    | prov7\n                    | prov8\n                    | prov9\n                    | prov10proverb_1 : ISSM1 FI3L1 HARF1 ISSM2proverb_2 : HARF2 FI3L2 ISSM3 FI3L3 ISSM4proverb_3 : ISSM5 MODAF1 HARF3 ISSM6 MODAF2proverb_4 : ISSM7 MODAF3 FI3L4 HARF1 ISSM8 MODAF2proverb_5 : FI3L5 MAF3OLBIH1 FA FI3L5 MAF3OLBIH2proverb_6 : FI3L6 HARF1 HARFNAFY FI3L7 MAF3OLBIH3 WAW HARFNAFY FI3L8 MAF3OLBIH4 proverb_7 : ISSM9 KHABAR1 HARF1 ISSM10proverb_8 : ISSM11 HARF1 ISSM12 MODAF4proverb_9 : FI3L9 MAF3OLBIH5 FI3L10proverb_10 : FI3L11 MAF3OLBIH6  ISSM13 HARF2 FI3L12prov1 :   DELIMITER proverb_1 prov2 :   DELIMITER proverb_2 prov3 :   DELIMITER proverb_3 prov4 :   DELIMITER proverb_4 prov5 :   DELIMITER proverb_5 prov6 :   DELIMITER proverb_6prov7 :   DELIMITER proverb_7prov8 :   DELIMITER proverb_8prov9 :   DELIMITER proverb_9prov10 :   DELIMITER proverb_10'
    
_lr_action_items = {'ISSM1':([0,32,],[22,22,]),'HARF2':([0,32,62,],[23,23,71,]),'ISSM5':([0,32,],[24,24,]),'ISSM7':([0,32,],[25,25,]),'FI3L5':([0,32,57,],[26,26,67,]),'FI3L6':([0,32,],[27,27,]),'ISSM9':([0,32,],[28,28,]),'ISSM11':([0,32,],[29,29,]),'FI3L9':([0,32,],[30,30,]),'FI3L11':([0,32,],[31,31,]),'DELIMITER':([0,],[32,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,43,44,45,46,47,48,49,50,51,52,61,63,69,70,72,73,75,77,78,82,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-31,-32,-33,-34,-35,-36,-37,-38,-39,-40,-29,-21,-27,-28,-22,-23,-25,-30,-24,-26,]),'FI3L1':([22,],[33,]),'FI3L2':([23,],[34,]),'MODAF1':([24,],[35,]),'MODAF3':([25,],[36,]),'MAF3OLBIH1':([26,],[37,]),'HARF1':([27,29,33,39,56,],[38,40,53,59,66,]),'KHABAR1':([28,],[39,]),'MAF3OLBIH5':([30,],[41,]),'MAF3OLBIH6':([31,],[42,]),'ISSM3':([34,],[54,]),'HARF3':([35,],[55,]),'FI3L4':([36,],[56,]),'FA':([37,],[57,]),'HARFNAFY':([38,79,],[58,80,]),'ISSM12':([40,],[60,]),'FI3L10':([41,],[61,]),'ISSM13':([42,],[62,]),'ISSM2':([53,],[63,]),'FI3L3':([54,],[64,]),'ISSM6':([55,],[65,]),'FI3L7':([58,],[68,]),'ISSM10':([59,],[69,]),'MODAF4':([60,],[70,]),'ISSM4':([64,],[72,]),'MODAF2':([65,74,],[73,78,]),'ISSM8':([66,],[74,]),'MAF3OLBIH2':([67,],[75,]),'MAF3OLBIH3':([68,],[76,]),'FI3L12':([71,],[77,]),'WAW':([76,],[79,]),'FI3L8':([80,],[81,]),'MAF3OLBIH4':([81,],[82,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'proverb':([0,],[1,]),'proverb_1':([0,32,],[2,43,]),'proverb_2':([0,32,],[3,44,]),'proverb_3':([0,32,],[4,45,]),'proverb_4':([0,32,],[5,46,]),'proverb_5':([0,32,],[6,47,]),'proverb_6':([0,32,],[7,48,]),'proverb_7':([0,32,],[8,49,]),'proverb_8':([0,32,],[9,50,]),'proverb_9':([0,32,],[10,51,]),'proverb_10':([0,32,],[11,52,]),'prov1':([0,],[12,]),'prov2':([0,],[13,]),'prov3':([0,],[14,]),'prov4':([0,],[15,]),'prov5':([0,],[16,]),'prov6':([0,],[17,]),'prov7':([0,],[18,]),'prov8':([0,],[19,]),'prov9':([0,],[20,]),'prov10':([0,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> proverb","S'",1,None,None,None),
  ('proverb -> proverb_1','proverb',1,'p_proverb','testyacc.py',21),
  ('proverb -> proverb_2','proverb',1,'p_proverb','testyacc.py',22),
  ('proverb -> proverb_3','proverb',1,'p_proverb','testyacc.py',23),
  ('proverb -> proverb_4','proverb',1,'p_proverb','testyacc.py',24),
  ('proverb -> proverb_5','proverb',1,'p_proverb','testyacc.py',25),
  ('proverb -> proverb_6','proverb',1,'p_proverb','testyacc.py',26),
  ('proverb -> proverb_7','proverb',1,'p_proverb','testyacc.py',27),
  ('proverb -> proverb_8','proverb',1,'p_proverb','testyacc.py',28),
  ('proverb -> proverb_9','proverb',1,'p_proverb','testyacc.py',29),
  ('proverb -> proverb_10','proverb',1,'p_proverb','testyacc.py',30),
  ('proverb -> prov1','proverb',1,'p_proverb','testyacc.py',31),
  ('proverb -> prov2','proverb',1,'p_proverb','testyacc.py',32),
  ('proverb -> prov3','proverb',1,'p_proverb','testyacc.py',33),
  ('proverb -> prov4','proverb',1,'p_proverb','testyacc.py',34),
  ('proverb -> prov5','proverb',1,'p_proverb','testyacc.py',35),
  ('proverb -> prov6','proverb',1,'p_proverb','testyacc.py',36),
  ('proverb -> prov7','proverb',1,'p_proverb','testyacc.py',37),
  ('proverb -> prov8','proverb',1,'p_proverb','testyacc.py',38),
  ('proverb -> prov9','proverb',1,'p_proverb','testyacc.py',39),
  ('proverb -> prov10','proverb',1,'p_proverb','testyacc.py',40),
  ('proverb_1 -> ISSM1 FI3L1 HARF1 ISSM2','proverb_1',4,'p_proverb_1','testyacc.py',48),
  ('proverb_2 -> HARF2 FI3L2 ISSM3 FI3L3 ISSM4','proverb_2',5,'p_proverb_2','testyacc.py',54),
  ('proverb_3 -> ISSM5 MODAF1 HARF3 ISSM6 MODAF2','proverb_3',5,'p_proverb_3','testyacc.py',58),
  ('proverb_4 -> ISSM7 MODAF3 FI3L4 HARF1 ISSM8 MODAF2','proverb_4',6,'p_proverb_4','testyacc.py',63),
  ('proverb_5 -> FI3L5 MAF3OLBIH1 FA FI3L5 MAF3OLBIH2','proverb_5',5,'p_proverb_5','testyacc.py',67),
  ('proverb_6 -> FI3L6 HARF1 HARFNAFY FI3L7 MAF3OLBIH3 WAW HARFNAFY FI3L8 MAF3OLBIH4','proverb_6',9,'p_proverb_6','testyacc.py',72),
  ('proverb_7 -> ISSM9 KHABAR1 HARF1 ISSM10','proverb_7',4,'p_proverb_7','testyacc.py',76),
  ('proverb_8 -> ISSM11 HARF1 ISSM12 MODAF4','proverb_8',4,'p_proverb_8','testyacc.py',81),
  ('proverb_9 -> FI3L9 MAF3OLBIH5 FI3L10','proverb_9',3,'p_proverb_9','testyacc.py',85),
  ('proverb_10 -> FI3L11 MAF3OLBIH6 ISSM13 HARF2 FI3L12','proverb_10',5,'p_proverb_10','testyacc.py',90),
  ('prov1 -> DELIMITER proverb_1','prov1',2,'p_prov1','testyacc.py',112),
  ('prov2 -> DELIMITER proverb_2','prov2',2,'p_prov2','testyacc.py',119),
  ('prov3 -> DELIMITER proverb_3','prov3',2,'p_prov3','testyacc.py',125),
  ('prov4 -> DELIMITER proverb_4','prov4',2,'p_prov4','testyacc.py',131),
  ('prov5 -> DELIMITER proverb_5','prov5',2,'p_prov5','testyacc.py',137),
  ('prov6 -> DELIMITER proverb_6','prov6',2,'p_prov6','testyacc.py',143),
  ('prov7 -> DELIMITER proverb_7','prov7',2,'p_prov7','testyacc.py',150),
  ('prov8 -> DELIMITER proverb_8','prov8',2,'p_prov8','testyacc.py',157),
  ('prov9 -> DELIMITER proverb_9','prov9',2,'p_prov9','testyacc.py',165),
  ('prov10 -> DELIMITER proverb_10','prov10',2,'p_prov10','testyacc.py',174),
]
